source_list:
  - /control/joint_states
  - /differential_side_joint_states
  - /dynamixel/joint_states
  - /motor/joint_states
  - /linear_actuator/joint_states
  - /camera_effector/joint_states
  - /dummy/joint_states
rate: 50
