<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" >

<!-- Differential ######################################################### -->

  <xacro:macro name="pandora_differential_plugin" 
               params="publish_joint_states" >
    <!-- ================================================================== -->
    <gazebo>

      <plugin name="PandoraDifferantialPlugin"
              filename="libpandora_differential_plugin.so" >

        <robotNamespace>${robot_namespace}</robotNamespace>
        
        <publishJointStates>${publish_joint_states}</publishJointStates>

        <baseLink>${base_link_name}_link</baseLink>
        <leftFrontWheelLink>left_front_${wheel_link_name}_link</leftFrontWheelLink>
        <leftRearWheelLink>left_rear_${wheel_link_name}_link</leftRearWheelLink>
        <rightFrontWheelLink>right_front_${wheel_link_name}_link</rightFrontWheelLink>
        <rightRearWheelLink>right_rear_${wheel_link_name}_link</rightRearWheelLink>
        <leftSideJoint>left_${side_joint_name}_joint</leftSideJoint>
        <rightSideJoint>right_${side_joint_name}_joint</rightSideJoint>

        <maxAngle>${side_joint_max_limit}</maxAngle>
        <sideJointDamping>${side_joint_damping}</sideJointDamping>

        <P>120.0</P>
        <I>0.005</I>
        <D>8.0</D>
        <correctionForceModifier>200.0</correctionForceModifier>
        <maxDownforce>0.0</maxDownforce>
        <maxDifferentialForceZ>0.0</maxDifferentialForceZ>
        <maxDifferentialForceY>0.0</maxDifferentialForceY>

      </plugin>

    </gazebo>
    <!-- ================================================================== -->
  </xacro:macro>

<!-- 3D Pose ############################################################## -->

  <xacro:macro name="pandora_p3d_plugin" >
    <!-- ================================================================== -->
    <gazebo>

      <plugin name="Pandora3dPosePlugin"
              filename="libpandora_p3d_plugin.so" >

        <robotNamespace>${robot_namespace}</robotNamespace>

        <bodyName>${base_link_name}_link</bodyName>

        <frameName>map</frameName>
        <topicName>perfect_pose</topicName>
        <broadcastTF>0</broadcastTF>

      </plugin>

    </gazebo>
    <!-- ================================================================== -->
  </xacro:macro>

<!-- Ros Imu ############################################################## -->

  <xacro:macro name="ros_imu_plugin" >
    <!-- ================================================================== -->
    <gazebo>

      <plugin name="RosImuPlugin"
              filename="libgazebo_ros_imu.so" >
        
        <updateRate>50.0</updateRate>
        
        <topicName>/sensors/imu</topicName>
        <serviceName>default_imu</serviceName>

        <robotNamespace>${robot_namespace}</robotNamespace>

        <bodyName>${base_link_name}_link</bodyName>
        
        <gaussianNoise>0.0</gaussianNoise>
        
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>

      </plugin>

    </gazebo>
    <!-- ================================================================== -->
  </xacro:macro>

<!-- Pandora Imu ########################################################## -->

  <xacro:macro name="pandora_imu_stabilizer_plugin" >
    <!-- ================================================================== -->
    <gazebo>

      <plugin name="PandoraImuStabilizerPlugin"
              filename="libpandora_imu_stabilizer_plugin.so" >
        
        <updateRate>50.0</updateRate>
        
        <topicName>/sensors/imu</topicName>
        <serviceName>default_imu</serviceName>

        <robotNamespace>${robot_namespace}</robotNamespace>

        <bodyName>${base_link_name}_link</bodyName>
        
        <rollCorrectionJoint>laser_roll_joint</rollCorrectionJoint>
        <pitchCorrectionJoint>laser_pitch_joint</pitchCorrectionJoint>
        
        <gaussianNoise>0.0</gaussianNoise>
        
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>

      </plugin>

    </gazebo>
    <!-- ================================================================== -->
  </xacro:macro>

<!-- Ros Control ########################################################## -->

  <xacro:macro name="gazebo_ros_control_plugin"
               params="hw_sim ns" >
    <!-- ================================================================== -->
    <gazebo>

      <plugin name="GazeboRosControl"
              filename="libgazebo_ros_control.so" >

      <!-- <robotNamespace>${robot_namespace}</robotNamespace> -->
      <robotNamespace>${ns}</robotNamespace>

      <robotSimType>${hw_sim}</robotSimType>

      </plugin>

    </gazebo>
    <!-- ================================================================== -->
  </xacro:macro>

<!-- Skid Steer Drive ##################################################### -->

  <xacro:macro name="ros_skid_steer_drive_plugin" >
    <!-- ================================================================== -->
    <gazebo>

      <plugin name="RosSkidSteerDrivePlugin"
              filename="libgazebo_ros_skid_steer_drive.so" >

        <robotNamespace>${robot_namespace}</robotNamespace>

        <updateRate>100.0</updateRate>

        <leftFrontJoint>left_front_${wheel_joint_name}_joint</leftFrontJoint>
        <rightFrontJoint>right_front_${wheel_joint_name}_joint</rightFrontJoint>
        <leftRearJoint>left_rear_${wheel_joint_name}_joint</leftRearJoint>
        <rightRearJoint>right_rear_${wheel_joint_name}_joint</rightRearJoint>

        <wheelSeparation>${wheel_separation}</wheelSeparation>
        <wheelDiameter>${ 2 * wheel_radius }</wheelDiameter>

        <torque>${wheel_joint_max_torque}</torque>

        <robotBaseFrame>${base_link_name}_link</robotBaseFrame>
        <topicName>cmd_vel</topicName>
        <broadcastTF>0</broadcastTF>
        <commandTopic>cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>

      </plugin>

    </gazebo>
    <!-- ================================================================== -->
  </xacro:macro>

<!-- ###################################################################### -->

</robot>
